'use strict';function x(g,a,b,d){g.A.qc(g.ab,a,b,d,void 0)}function F(g,a,b,d){g.A.ca?x(g,a,b,d):g.A.ef()._OnMessageFromDOM({type:"event",component:g.ab,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function H(g,a,b){g.A.C(g.ab,a,b)}function J(g,a){for(const [b,d]of a)H(g,b,d)}function K(g){g.Rb||(g.A.Qe(g.ae),g.Rb=!0)}window.Ra=class{constructor(g,a){this.A=g;this.ab=a;this.Rb=!1;this.ae=()=>this.Ca()}ed(){}Ca(){}};function L(g){-1!==g.Pa&&(self.clearTimeout(g.Pa),g.Pa=-1)}
window.He=class{constructor(g,a){this.Mc=g;this.ug=a;this.Pa=-1;this.Sb=-Infinity;this.be=()=>{this.Pa=-1;this.Sb=Date.now();this.gb=!0;this.Mc();this.gb=!1};this.Kd=this.gb=!1}c(){L(this);this.be=this.Mc=null}};"use strict";function N(g,a){H(g,"get-element",b=>{const d=g.ba.get(b.elementId);return a(d,b)})}
window.Pg=class extends self.Ra{constructor(g,a){super(g,a);this.ba=new Map;this.Lc=!0;J(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Lc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Lc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Lc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ba.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(f){const c=document.createElement("script");c.async=!1;c.type="module";return f.Fg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=f.Jg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=f;document.head.appendChild(c)})}let d=!1,h=!1;function m(){if(!d){try{new Worker("blob://",{get type(){h=!0}})}catch(f){}d=!0}return h}let p=
new Audio;const w={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(f){f=await B(f);return(new TextDecoder("utf-8")).decode(f)}function B(f){return new Promise((c,
k)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(f)})}const u=[];let v=0;window.RealFile=window.File;const C=[],G=new Map,z=new Map;let I=0;const D=[];self.runOnStartup=function(f){if("function"!==typeof f)throw Error("runOnStartup called without a function");D.push(f)};const M=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.Wa=class f{constructor(c){this.ca=c.Lg;this.oa=null;this.F="";this.dc=c.Ig;this.vb={};this.Ia=this.ub=null;
this.Pb=[];this.jb=this.G=this.Na=null;this.Ma=-1;this.zg=()=>this.Ef();this.La=[];this.v=c.ce;this.hb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Ub=this.ha=null;"html5"!==
this.v&&"playable-ad"!==this.v||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.nf(k));this.C("runtime",
"create-job-worker",()=>this.pf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.wd(c)):this.wd(c)}c(){this.wc();this.oa&&(this.oa=this.oa.onmessage=null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Ce(){return g&&"cordova"===this.v}pc(){const c=navigator.userAgent;return g&&M.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async wd(c){"macos-wkwebview"===
this.v&&this.Xf();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Ub={};await this.Ve();for(let l=0,n=c.Qa.length;l<n;++l){var k=c.Qa[l].toLowerCase();this.Ub.hasOwnProperty(k)?c.Qa[l]={Fg:!0,Jg:this.Ub[k]}:this.ha.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ha[k]))}}c.Ag?this.F=c.Ag:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Ng&&(this.vb=c.Ng);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Af(l));this.jb=new self.De(this);await O(this.jb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.gf(c,k.port2):await this.ff(c,k.port2)}zc(c){c=this.vb.hasOwnProperty(c)?this.vb[c]:c.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:
"playable-ad"===this.v&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async jc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.hb)return c=await this.xb(l.Eg?c:this.dc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),
l)}return new Worker(c,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}vd(c){var k=this.jb;return{baseUrl:this.F,windowInnerWidth:this.va(),windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ua(),projectData:c.Tg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Rg||"",exportType:c.ce,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.Sg,jobScheduler:{inputPort:k.Sc,outputPort:k.Yc,maxNumWorkers:k.wg},supportedAudioFormats:w,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.dc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.dc+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Ce(),isiOSWebView:this.pc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async gf(c,k){var l=this.zc(c.Mg);this.ub=await this.jc(l,this.F,{type:"module",name:"Runtime",
Eg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let n=c.dd||[],t=c.Qa;n=await Promise.all(n.map(q=>this.Da(q)));t=await Promise.all(t.map(q=>this.Da(q)));if("cordova"===this.v)for(let q=0,r=c.hc.length;q<r;++q){const y=c.hc[q],E=y[0];if(E===c.bd||"scriptsInEvents.js"===E||E.endsWith("/scriptsInEvents.js"))y[1]=await this.Da(E)}this.ub.postMessage(Object.assign(this.vd(c),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:c.hc,mainProjectScript:c.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...P(this.jb)]);this.Pb=C.map(q=>new q(this));this.ud();self.c3_callFunction=(q,r)=>this.Na.hf(q,r);"preview"===this.v&&(self.goToLastErrorScript=()=>this.qc("runtime","go-to-last-error-script"))}async ff(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=
this.G;this.Pb=C.map(q=>new q(this));this.ud();var l=c.Qa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.dd)&&l.unshift(...c.dd);l=await Promise.all(l.map(q=>this.Da(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=c.bd,t=c.hc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Da(r),await b(r),"preview"!==this.v||l[q]||this.Ed(q,"main script did not run to completion")}catch(y){this.Ed(q,y)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))r=
await this.Da(r),await b(r);"preview"===this.v&&"object"!==typeof self.Og.Qg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.vd(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:D}),this.yd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Ed(c,
k){this.Jb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Jb()}Jb(){const c=window.Bg;c&&(c.parentElement.removeChild(c),window.Bg=null)}async pf(){const c=await Q(this.jb);return{outputPort:c,transferables:[c]}}ef(){if(this.ca)throw Error("not available in worker mode");return this.Ia}qc(c,k,l,n,t){this.oa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}nd(c,k,l,n,t){const q=I++,r=new Promise((y,E)=>{z.set(q,{resolve:y,reject:E})});this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.uf(c);if("result"===k)this.Hf(c);else if("runtime-ready"===k)this.If();else if("alert-error"===k)this.Jb(),alert(c.message);else if("creating-runtime"===k)this.yd();else throw Error(`unknown message '${k}'`);
}uf(c){const k=c.component,l=c.handler,n=c.data,t=c.responseId;if(c=G.get(k))if(c=c.get(l)){var q=null;try{q=c(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Ib(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Ib(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Ib(t,!1,""+r)}):this.Ib(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(c,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.oa.postMessage({type:"result",responseId:c,isOk:k,result:l},n)}Hf(c){const k=c.responseId,l=c.isOk;c=c.result;const n=z.get(k);l?n.resolve(c):n.reject(c);z.delete(k)}C(c,k,l){let n=G.get(c);n||(n=new Map,G.set(c,n));if(n.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);n.set(k,l)}static wb(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}ud(){for(const c of this.Pb)if("runtime"===c.ab){this.Na=c;return}throw Error("cannot find runtime DOM handler");
}Af(c){this.qc("debugger","message",c)}If(){for(const c of this.Pb)c.ed()}static Ua(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Fd(c){e=!!c}Qe(c){this.La.push(c);this.Jc()}Uf(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.wc()}Jc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.zg))}wc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Ef(){this.Ma=
-1;for(const c of this.La)c();this.Jc()}ta(c){this.Na.ta(c)}Ba(c){this.Na.Ba(c)}Ic(){this.Na.Ic()}Db(c){this.Na.Db(c)}Be(){return!!w["audio/webm; codecs=opus"]}async sg(c){c=await this.nd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ae(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}md(c){return!this.Ae(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.hb&&this.md(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async nf(c){const k=c.filename;switch(c.as){case "text":return await this.te(k);case "buffer":return await this.xb(k);default:throw Error("unsupported type");}}hd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async te(c){c=await this.hd(c);return await A(c)}xc(){if(u.length&&!(8<=v)){v++;var c=u.shift();
this.We(c.filename,c.Kg,c.Dg)}}xb(c){return new Promise((k,l)=>{u.push({filename:c,Kg:n=>{v--;this.xc();k(n)},Dg:n=>{v--;this.xc();l(n)}});this.xc()})}async We(c,k,l){try{const n=await this.hd(c),t=await B(n);k(t)}catch(n){l(n)}}Xf(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ve(){const c=
[];for(const [k,l]of Object.entries(this.ha))c.push(this.Ue(k,l));await Promise.all(c)}async Ue(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Ub[c]=k.str;else{let l=await this.cf(k);l||(l=this.Ye(k));this.ha[c]=l}}async cf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}Ye(c){c=this.Of(c);return this.Te(c.data,c.Gg)}Of(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Gg:c,data:l}}Te(c,k){var l=c.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,y;for(y=r=0;r<n;++r)q[r]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=
3;l--;)t[y]=c.charCodeAt(y),++y;return new Blob([t],{type:k})}}}"use strict";
{const g=self.Wa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((f,c)=>{const k=document.createElement("link");k.onload=()=>f(k);k.onerror=l=>c(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function w(e){return new Promise((f,c)=>{const k=new Image;k.onload=()=>f(k);k.onerror=l=>c(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((f,c)=>{let k=new FileReader;k.onload=l=>f(l.target.result);k.onerror=l=>c(l);k.readAsText(e)})}async function u(e,f,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(e)}l.setAttribute("width",f+"px");l.setAttribute("height",c+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function v(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function z(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function I(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const f=e.getBoundingClientRect();document.body.removeChild(e);return[f.width,
f.height]}};self.C3_RasterSvgImageBlob=async function(e,f,c,k,l){e=await u(e,f,c);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,f,c);return n};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.wb(class extends self.Ra{constructor(e){super(e,"runtime");this.Pd=!0;this.Oa=-1;this.$c="any";this.Gd=this.Hd=!1;this.Ha=
this.rb=this.xa=null;this.$b=this.Zb=0;e.C("canvas","update-size",k=>this.Lf(k));e.C("runtime","invoke-download",k=>this.yf(k));e.C("runtime","raster-svg-image",k=>this.Ff(k));e.C("runtime","get-svg-image-size",k=>this.wf(k));e.C("runtime","set-target-orientation",k=>this.Jf(k));e.C("runtime","register-sw",()=>this.Gf());e.C("runtime","post-to-debugger",k=>this.Ad(k));e.C("runtime","go-to-script",k=>this.Ad(k));e.C("runtime","before-start-ticking",()=>this.mf());e.C("runtime","debug-highlight",k=>
this.qf(k));e.C("runtime","enable-device-orientation",()=>this.Se());e.C("runtime","enable-device-motion",()=>this.Re());e.C("runtime","add-stylesheet",k=>this.kf(k));e.C("runtime","alert",k=>this.lf(k));e.C("runtime","hide-cordova-splash",()=>this.xf());const f=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;f.has(l.tagName.toLowerCase())||v(l)||k.preventDefault()});const c=e.G;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",
z);c.addEventListener("selectstart",z);c.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),c.addEventListener("pointerdown",z)):c.addEventListener("touchstart",z);this.ob=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",
()=>this.Mf());window.addEventListener("fullscreenchange",()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",k=>this.Ec(k));window.addEventListener("webkitfullscreenerror",k=>this.Ec(k));window.addEventListener("mozfullscreenerror",k=>this.Ec(k));e.pc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):v(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Nf(k);this.Ja=new Set;this.Vb=new WeakSet;this.na=!1}mf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Hc(!0)),document.addEventListener("resume",()=>this.Hc(!1))):document.addEventListener("visibilitychange",()=>this.Hc(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}ed(){window.addEventListener("focus",()=>
this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:M()});this.ob=0});window.addEventListener("focusin",f=>{f=f.target;(C.has(f.tagName.toLowerCase())||v(f))&&this.Za("keyboard-blur")});window.addEventListener("keydown",f=>this.zd("keydown",f));window.addEventListener("keyup",f=>this.zd("keyup",f));window.addEventListener("dblclick",f=>this.Fc("dblclick",f,d));window.addEventListener("wheel",f=>this.Cf(f));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
f=>{this.Ac(f);this.Ya("pointerdown",f)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.He(()=>this.af(),5),this.rb.Kd=!0,window.addEventListener("pointerrawupdate",f=>this.Df(f))):window.addEventListener("pointermove",f=>this.Ya("pointermove",f)),window.addEventListener("pointerup",f=>this.Ya("pointerup",f)),window.addEventListener("pointercancel",f=>this.Ya("pointercancel",f))):(window.addEventListener("mousedown",f=>{this.Ac(f);this.Gc("pointerdown",
f)}),window.addEventListener("mousemove",f=>this.Gc("pointermove",f)),window.addEventListener("mouseup",f=>this.Gc("pointerup",f)),window.addEventListener("touchstart",f=>{this.Ac(f);this.Hb("pointerdown",f)}),window.addEventListener("touchmove",f=>this.Hb("pointermove",f)),window.addEventListener("touchend",f=>this.Hb("pointerup",f)),window.addEventListener("touchcancel",f=>this.Hb("pointercancel",f)));const e=()=>this.Ic();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Za(e,f){x(this,e,f||null,m)}va(){return this.A.va()}ua(){return this.A.ua()}Mf(){const e=this.va(),f=this.ua();this.Za("window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ua()});this.A.pc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Bd(e,f,0))}Vf(e,f,c){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Bd(e,
f,c),48)}Bd(e,f,c){const k=this.va(),l=this.ua();this.Oa=-1;k!=e||l!=f?this.Za("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ua()}):10>c&&this.Vf(k,l,c+1)}Jf(e){this.$c=e.targetOrientation}og(){const e=this.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(e):screen.webkitLockOrientation?
f=screen.webkitLockOrientation(e):screen.mozLockOrientation?f=screen.mozLockOrientation(e):screen.msLockOrientation&&(f=screen.msLockOrientation(e));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}Xa(){const e=g.Ua();e&&"any"!==this.$c&&this.og();x(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Ec(e){console.warn("[Construct 3] Fullscreen request failed: ",e);x(this,"fullscreenerror",
{isFullscreen:g.Ua(),innerWidth:this.va(),innerHeight:this.ua()})}Hc(e){e?this.A.wc():this.A.Jc();x(this,"visibilitychange",{hidden:e})}zd(e,f){"Backspace"===f.key&&z(f);const c=b.get(f.code)||f.code;F(this,e,{code:c,key:f.key,which:f.which,repeat:f.repeat,altKey:f.altKey,ctrlKey:f.ctrlKey,metaKey:f.metaKey,shiftKey:f.shiftKey,timeStamp:f.timeStamp},d)}Cf(e){x(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Fc(e,f,c){a(f)||F(this,e,{button:f.button,buttons:f.buttons,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:f.movementX||0,movementY:f.movementY||0,timeStamp:f.timeStamp},c)}Gc(e,f){if(!a(f)){var c=this.ob;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===e&&0!==f.buttons&&(e="pointermove");F(this,e,{pointerId:1,pointerType:"mouse",button:f.button,buttons:f.buttons,lastButtons:c,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,
movementX:f.movementX||0,movementY:f.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:f.timeStamp},d);this.ob=f.buttons;this.Fc(f.type,f,h)}}Ya(e,f){if(this.rb&&"pointermove"!==e){var c=this.rb;c.gb||(L(c),c.Sb=Date.now())}c=0;"mouse"===f.pointerType&&(c=this.ob);F(this,e,{pointerId:f.pointerId,pointerType:f.pointerType,button:f.button,buttons:f.buttons,lastButtons:c,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:(f.movementX||
0)+this.Zb,movementY:(f.movementY||0)+this.$b,width:f.width||0,height:f.height||0,pressure:f.pressure||0,tangentialPressure:f.tangentialPressure||0,tiltX:f.tiltX||0,tiltY:f.tiltY||0,twist:f.twist||0,timeStamp:f.timeStamp},d);this.$b=this.Zb=0;"mouse"===f.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Fc(c,f,h),this.ob=f.buttons)}Df(e){this.Ha&&(this.Zb+=this.Ha.movementX||0,this.$b+=this.Ha.movementY||0);this.Ha=e;e=this.rb;if(-1===e.Pa){var f=Date.now(),
c=f-e.Sb,k=e.ug;c>=k&&e.Kd?(e.Sb=f,e.gb=!0,e.Mc(),e.gb=!1):e.Pa=self.setTimeout(e.be,Math.max(k-c,4))}}af(){this.Ya("pointermove",this.Ha);this.Ha=null}Hb(e,f){for(let c=0,k=f.changedTouches.length;c<k;++c){const l=f.changedTouches[c];F(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:f.movementX||0,movementY:f.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:f.timeStamp},d)}}Ac(e){window!==window.top&&window.focus();this.xd(e.target)&&document.activeElement&&!this.xd(document.activeElement)&&document.activeElement.blur()}xd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Se(){this.Hd||(this.Hd=!0,window.addEventListener("deviceorientation",e=>this.sf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.tf(e)))}Re(){this.Gd||(this.Gd=!0,window.addEventListener("devicemotion",e=>this.rf(e)))}sf(e){x(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}tf(e){x(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}rf(e){let f=null;var c=e.acceleration;c&&(f=
{x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.accelerationIncludingGravity;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});x(this,"devicemotion",{acceleration:f,accelerationIncludingGravity:c,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},d)}Lf(e){const f=this.A.G;f.style.width=e.styleWidth+"px";f.style.height=e.styleHeight+"px";f.style.marginLeft=e.marginLeft+"px";f.style.marginTop=e.marginTop+"px";this.Pd&&(f.style.display=
"",this.Pd=!1)}yf(e){const f=e.url;e=e.filename;const c=document.createElement("a"),k=document.body;c.textContent=e;c.href=f;c.download=e;k.appendChild(c);c.click();k.removeChild(c)}async Ff(e){var f=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);f=f?await createImageBitmap(e,f):await createImageBitmap(e);return{imageBitmap:f,transferables:[f]}}async wf(e){return await self.C3_GetSvgImageSize(e.blob)}async kf(e){await p(e.url)}Ic(){var e=
[...this.Ja];this.Ja.clear();if(!this.na)for(const f of e)(e=f.play())&&e.catch(()=>{this.Vb.has(f)||this.Ja.add(f)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Vb.delete(e);let f;try{f=e.play()}catch(c){this.Ja.add(e);return}f&&f.catch(()=>{this.Vb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);this.Vb.add(e)}Db(e){this.na=!!e}xf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}qf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),
this.xa.id="inspectOutline",document.body.appendChild(this.xa));var f=this.xa;f.style.display="";f.style.left=e.left-1+"px";f.style.top=e.top-1+"px";f.style.width=e.width+2+"px";f.style.height=e.height+2+"px";f.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Gf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}hf(e,f){return this.A.nd(this.ab,"js-invoke-function",{name:e,params:f},void 0,void 0)}lf(e){alert(e.message)}Nf(e){"entered-fullscreen"===
e?(g.Fd(!0),this.Xa()):"exited-fullscreen"===e?(g.Fd(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function O(g){if(g.tg)throw Error("already initialised");g.tg=!0;var a=g.cc.zc("dispatchworker.js");g.Oc=await g.cc.jc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Sc=a.port1;g.Oc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Yc=await Q(g)}function P(g){return[g.Sc,g.Yc]}
async function Q(g){const a=g.Qd.length;var b=g.cc.zc("jobworker.js");b=await g.cc.jc(b,g.F,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;g.Oc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);g.Qd.push(b);return h.port1}
self.De=class{constructor(g){this.cc=g;this.F=g.F;this.F="preview"===g.v?this.F+"workers/":this.F+g.dc;this.wg=Math.min(navigator.hardwareConcurrency||2,16);this.Oc=null;this.Qd=[];this.Yc=this.Sc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Wa({Lg:!0,Mg:"workermain.js",Qa:["scripts/c3runtime.js"],hc:[],bd:"",Ig:"scripts/",dd:[],ce:"html5"}));"use strict";
self.Wa.wb(class extends self.Ra{constructor(g){super(g,"mouse");J(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.A.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{x(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{x(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function R(g,a){a=a.type;let b=!0;0===a?b=await S():1===a&&(b=await T());x(g,"permission-result",{type:a,result:b})}async function S(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function T(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Wa.wb(class extends self.Ra{constructor(g){super(g,"touch");H(this,"request-permission",a=>R(this,a))}});"use strict";
{const g=180/Math.PI;self.da=class extends self.Ra{constructor(a){super(a,"audio");this.Ob=this.f=null;this.Qb=this.Rc=!1;this.qa=()=>this.pg();this.$=[];this.D=[];this.ga=null;this.Rd="";this.Sd=-1;this.qb=new Map;this.Vc=1;this.na=!1;this.ad=0;this.ec=1;this.Pc=0;this.Ud="HRTF";this.Ld="inverse";this.Vd=600;this.Td=1E4;this.Xd=1;this.Nd=this.Zc=!1;this.$d=this.A.Be();this.aa=new Map;this.Fa=new Set;this.Tc=!1;this.Wc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Bf(b,d);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.vf();self.C3Audio_DOMInterface=this;J(this,[["create-audio-context",b=>this.Xe(b)],["play",b=>this.Pf(b)],["stop",b=>this.mg(b)],["stop-all",()=>this.ng()],["set-paused",b=>this.fg(b)],["set-volume",b=>this.kg(b)],["fade-volume",b=>this.bf(b)],["set-master-volume",b=>this.dg(b)],["set-muted",b=>this.eg(b)],["set-silent",b=>this.hg(b)],["set-looping",b=>this.cg(b)],["set-playback-rate",b=>this.gg(b)],["seek",b=>this.Wf(b)],["preload",b=>this.Qf(b)],["unload",b=>
this.qg(b)],["unload-all",()=>this.rg()],["set-suspended",b=>this.ig(b)],["add-effect",b=>this.sd(b)],["set-effect-param",b=>this.$f(b)],["remove-effects",b=>this.Sf(b)],["tick",b=>this.Kf(b)],["load-state",b=>this.zf(b)]])}async Xe(a){a.isiOSCordova&&(this.Zc=!0);this.ad=a.timeScaleMode;this.Ud=["equalpower","HRTF","soundfield"][a.panningModel];this.Ld=["linear","inverse","exponential"][a.distanceModel];this.Vd=a.refDistance;this.Td=a.maxDistance;this.Xd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.$d||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.td();this.f.onstatechange=()=>{"running"!==this.f.state&&this.td()};this.Ob=this.f.createGain();this.Ob.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.kc();try{await Promise.all(a.preloadList.map(d=>this.Fb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}td(){this.Qb||(this.Rc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Qb=!0)}Ze(){this.Qb&&(this.Rc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Qb=!1)}pg(){if(!this.Rc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ze()}}W(){return this.f}kc(){return this.f.currentTime}ra(){return this.Ob}kd(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ra()}de(a,b){a=a.toLowerCase();let d=this.aa.get(a);
d||(d=[],this.aa.set(a,d));b.bg(d.length);b.jg(a);d.push(b);this.Dd(a)}Dd(a){let b=this.ra();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let h=0,m=d.length;h<m;++h){const p=d[h];h+1===m?p.S(this.ra()):p.S(d[h+1].P())}}for(const h of this.la(a))h.Ie(b);this.ya&&this.Wc===a&&(this.ya.disconnect(),this.ya.connect(b))}zb(){return this.Vc}Ab(){return this.na}ag(){this.Nd=!0}ve(a,b){return b?this.A.sg(a).then(d=>{const h=this.f.createBuffer(1,d.length,48E3);h.getChannelData(0).set(d);return h}):
new Promise((d,h)=>{this.f.decodeAudioData(a,d,h)})}ta(a){this.A.ta(a)}Ba(a){this.A.Ba(a)}od(a){let b=0;for(let d=0,h=this.D.length;d<h;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Je(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const h=this.$[b];this.$[a]=h;h.sa()?h.c():++a}this.$.length=a}*la(a){if(a)for(const b of this.D)self.da.we(b.Y,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Fb(a,b,d,h,m){for(const p of this.$)if(p.Ta()===b)return await U(p),p;
if(m)return null;h&&(this.Zc||this.Nd)&&this.Je();m="audio/webm; codecs=opus"===d&&!this.$d;h&&m&&this.ag();a=!h||this.Zc||m?new self.re(this,a,b,d,h,m):new self.pe(this,a,b,d,h);this.$.push(a);await U(a);return a}async yc(a,b,d,h,m){for(const p of this.D)if(p.Ta()===b&&(p.ic()||m))return p.Le(h),p;a=await this.Fb(a,b,d,m);h="html5"===a.Kc?new self.qe(a.i,a,h):new self.se(a.i,a,h);this.D.push(h);return h}Pe(a){let b=this.qb.get(a);if(!b){let d=null;b={cd:0,Hg:new Promise(h=>d=h),resolve:d};this.qb.set(a,
b)}b.cd++}Tf(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.cd--;0===b.cd&&(b.resolve(),this.qb.delete(a))}vc(a){a||(a=this.Rd);return(a=this.qb.get(a))?a.Hg:Promise.resolve()}Gb(){if(0<this.Fa.size)K(this);else for(const a of this.D)if(a.ld()){K(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.kc();for(var b of this.D)b.Ca(a);b=this.D.filter(d=>d.ld()).map(d=>d.Sa());x(this,"state",{tickCount:this.Sd,audioInstances:b,analysers:[...this.Fa].map(d=>d.ye())});0===b.length&&
0===this.Fa.size&&this.Rb&&(this.A.Uf(this.ae),this.Rb=!1)}rc(a,b,d){x(this,"trigger",{type:a,tag:b,aiid:d})}async Pf(a){const b=a.originalUrl,d=a.url,h=a.type,m=a.isMusic,p=a.tag,w=a.isLooping,A=a.vol,B=a.pos,u=a.panning;let v=a.off;0<v&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),v=v-a.performanceTime/1E3+a.contextTime):v=v-performance.now()/1E3+this.f.currentTime);this.Rd=p;this.Pe(p);try{this.ga=await this.yc(b,d,h,p,m),u?(this.ga.Cb(!0),this.ga.Ke(u.x,u.y,u.angle,
u.innerAngle,u.outerAngle,u.outerGain),u.hasOwnProperty("uid")&&this.ga.Me(u.uid)):this.ga.Cb(!1),this.ga.Play(w,A,B,v)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Tf(p)}K(this)}mg(a){a=a.tag;for(const b of this.la(a))b.ma()}ng(){for(const a of this.D)a.ma()}fg(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Va():d.Bb();this.Gb()}kg(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Eb(a)}async bf(a){const b=a.tag,d=a.vol,h=a.duration;
a=a.stopOnEnd;await this.vc(b);for(const m of this.la(b))m.xe(d,h,a);this.Gb()}dg(a){this.Vc=a.vol;for(const b of this.D)b.Lb()}eg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.pd(a)}hg(a){this.na=a.isSilent;this.A.Db(this.na);for(const b of this.D)b.Kb()}cg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.tc(a)}async gg(a){const b=a.tag;a=a.rate;await this.vc(b);for(const d of this.la(b))d.rd(a)}async Wf(a){const b=a.tag;a=a.pos;await this.vc(b);for(const d of this.la(b))d.sc(a)}async Qf(a){const b=
a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.yc(b,d,h,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async qg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}rg(){for(const a of this.$)a.c();this.$.length=0}ig(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.uc(a);a&&this.f.suspend&&this.f.suspend()}Kf(a){this.ec=a.timeScale;this.Pc=a.gameTime;this.Sd=a.tickCount;if(0!==this.ad)for(var b of this.D)b.Ea();
(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.D)h.fa===a&&h.qd(d.x,d.y,d.angle)}}async sd(a){var b=a.type;const d=a.tag;var h=a.params;if("filter"===b)h=new self.je(this,...h);else if("delay"===b)h=new self.he(this,...h);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}h=new self.ge(this,b.Z,
...h);h.Yf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.ke(this,...h);else if("phaser"===b)h=new self.me(this,...h);else if("gain"===b)h=new self.le(this,...h);else if("tremolo"===b)h=new self.oe(this,...h);else if("ringmod"===b)h=new self.ne(this,...h);else if("distortion"===b)h=new self.ie(this,...h);else if("compressor"===b)h=new self.fe(this,...h);else if("analyser"===b)h=new self.ee(this,...h);else throw Error("invalid effect type");this.de(d,h);this.Cd()}$f(a){const b=
a.index,d=a.param,h=a.value,m=a.ramp,p=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,h,m,p),this.Cd())}Sf(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.c();this.aa.delete(a);this.Dd(a)}}Oe(a){this.Fa.add(a);this.Gb()}Rf(a){this.Fa.delete(a)}Cd(){this.Tc||(this.Tc=!0,Promise.resolve().then(()=>this.$e()))}$e(){const a={};for(const [b,d]of this.aa)a[b]=d.map(h=>h.Sa());x(this,"fxstate",{fxstate:a});this.Tc=!1}async zf(a){const b=a.saveLoadMode;if(3!==
b)for(var d of this.D)d.sa()&&1===b||(d.sa()||2!==b)&&d.ma();for(const h of this.aa.values())for(const m of h)m.c();this.aa.clear();this.ec=a.timeScale;this.Pc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.na=a.isSilent;this.A.Db(this.na);this.Vc=a.masterVolume;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(m=>this.sd(m))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.jf(h,b)));this.Gb()}async jf(a,b){if(3!==b){var d=a.bufferOriginalUrl,
h=a.bufferUrl,m=a.bufferType,p=a.isMusic,w=a.tag,A=a.isLooping,B=a.volume,u=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.yc(d,h,m,w,p)}catch(v){console.error("[Construct 3] Audio: error loading audio state: ",v);return}b.Ge(a.pan);b.Play(A,B,u,0);a.isPlaying||b.Va();b.Cc(a)}}}Bf(a,b){this.ya&&this.ya.disconnect();this.Wc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.kd(this.Wc))}vf(){this.Nb||(this.Nb=this.f.createMediaStreamDestination(),this.Ob.connect(this.Nb));
return this.Nb.stream}static we(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ne(a){return a*g}static ue(a){return Math.pow(10,a/20)}static jd(a){return Math.max(Math.min(self.da.ue(a),1),0)}static Fe(a){return Math.log(a)/Math.log(10)*20}static Ee(a){return self.da.Fe(Math.max(Math.min(a,1),0))}static Cg(a,b){return 1-Math.exp(-b*a)}};self.Wa.wb(self.da)}"use strict";function U(g){g.Tb||(g.Tb=g.Bc());return g.Tb}
self.fd=class{constructor(g,a,b,d,h){this.i=g;this.yg=a;this.za=b;this.R=d;this.vg=h;this.Kc="";this.Tb=null}c(){this.Tb=this.i=null}Bc(){}W(){return this.i.W()}mc(){return this.yg}Ta(){return this.za}lc(){return this.R}sa(){return this.vg}ea(){}};"use strict";
self.pe=class extends self.fd{constructor(g,a,b,d,h){super(g,a,b,d,h);this.Kc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.kb=this.lb=null;this.K.addEventListener("canplaythrough",()=>!0);this.pb=this.W().createGain();this.nb=null;this.K.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.K&&(this.nb=this.W().createMediaElementSource(this.K),this.nb.connect(this.pb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.za}' error: `,m);this.kb&&(this.kb(m),this.kb=this.lb=null)})}c(){this.i.od(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.c()}Bc(){return new Promise((g,a)=>{this.lb=g;this.kb=a;this.K.src=this.za})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function V(g){if(g.wa)return g.wa;var a=g.i.A;if("cordova"===a.v&&a.md(g.za)&&a.hb)g.wa=await a.xb(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function W(g){if(g.Z)return g.Z;g.Z=await g.i.ve(g.wa,g.xg);g.wa=null}
self.re=class extends self.fd{constructor(g,a,b,d,h,m){super(g,a,b,d,h);this.Kc="webaudio";this.Z=this.wa=null;this.xg=!!m}c(){this.i.od(this);this.Z=this.wa=null;super.c()}async Bc(){try{await V(this),await W(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let g=0;self.gd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Mb=g++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.ib=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.I=!0;this.V=this.ka=this.H=!1;this.tb=1;this.Ga=!1;this.pa=1;a=this.i.ad;this.Uc=1===a&&!this.sa()||2===a;this.eb=this.fa=-1;this.Zd=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.kd(this.Y)}zb(){return this.i.zb()}yb(){return this.Uc?
this.i.Pc:performance.now()/1E3}mc(){return this.L.mc()}Ta(){return this.L.Ta()}lc(){return this.L.lc()}sa(){return this.L.sa()}Le(a){this.Y=a}T(){}ic(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}ld(){return!this.I&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Va(){}Bb(){}Eb(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.nc()}xe(a,b,d){if(!this.Ga){a*=this.zb();var h=this.M.gain;h.cancelScheduledValues(0);var m=this.i.kc();b=m+b;h.setValueAtTime(h.value,
m);h.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.Zd=d}}Lb(){this.Eb(this.tb)}Ca(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.Zd&&this.ma(),this.i.rc("fade-ended",this.Y,this.Mb))}nc(){const a=this.tb*this.zb();return isFinite(a)?a:0}pd(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Kb())}Ab(){return this.i.Ab()}Kb(){}tc(){}rd(a){this.pa!==a&&(this.pa=a,this.Ea())}Ea(){}sc(){}uc(){}Cb(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Ud,this.B.distanceModel=
this.i.Ld,this.B.refDistance=this.i.Vd,this.B.maxDistance=this.i.Td,this.B.rolloffFactor=this.i.Xd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Ke(a,b,d,h,m,p){this.ib&&(this.qd(a,b,d),a=self.da.Ne,this.B.coneInnerAngle=a(h),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}qd(a,b,d){this.ib&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Me(a){this.fa=a}oc(){}Ie(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Sa(){return{aiid:this.Mb,tag:this.Y,duration:this.ea(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.mc(),bufferUrl:"",bufferType:this.lc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.oc(),pan:this.ze()}}Cc(a){this.rd(a.playbackRate);this.pd(a.isMuted)}ze(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ge(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Cb(!1)}}}"use strict";
self.qe=class extends self.gd{constructor(g,a,b){super(g,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.ma();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.I=!0;this.fa=-1;this.i.rc("ended",this.Y,this.Mb)}T(){return this.O().ended}ic(){return this.I?!0:this.T()}Aa(){let g=this.O().currentTime;this.V||(g=Math.min(g,this.ea()));return g}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Eb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ta()}' to position '${b}': `,h)}this.i.ta(d);this.H=this.I=!1;this.V=g;this.pa=1}ma(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.I=!0;this.H=!1;this.fa=-1}Va(){if(!(this.H||this.I||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0}}Bb(){!this.H||this.I||this.T()||(this.i.ta(this.O()),this.H=!1)}Kb(){this.O().muted=this.Ga||this.Ab()}tc(g){g=!!g;this.V!==g&&
(this.V=g,this.O().loop=g)}Ea(){let g=this.pa;this.Uc&&(g*=this.i.ec);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}sc(g){if(!this.I&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}oc(){return this.Aa()}uc(g){g?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function X(g){g.j&&g.j.disconnect();g.j=null;g.$a=null}
self.se=class extends self.gd{constructor(g,a,b){super(g,a,b);this.j=null;this.Wb=d=>this.Dc(d);this.Qc=!0;this.$a=null;this.N=this.Xb=this.Yb=0;this.Xc=1}c(){this.ma();X(this);this.Wb=null;super.c()}Dc(g){this.H||this.ka||g.target!==this.$a||(this.I=this.Qc=!0,this.fa=-1,X(this),this.i.rc("ended",this.Y,this.Mb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Qc}ic(){return!this.j||this.I?!0:this.T()}Aa(){let g;g=this.H?this.N:this.Xb+(this.yb()-this.Yb)*this.pa;this.V||(g=Math.min(g,this.ea()));
return g}Play(g,a,b,d){this.Xc=1;this.Eb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.Wb;this.j.loop=g;this.j.start(d,b);this.H=this.I=this.Qc=!1;this.V=g;this.pa=1;this.Yb=this.yb();this.Xb=b}ma(){if(this.j)try{this.j.stop(0)}catch(g){}this.I=!0;this.H=!1;this.fa=-1}Va(){this.H||this.I||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Bb(){!this.H||this.I||this.T()||(X(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Yb=this.yb(),this.Xb=this.N,this.H=!1)}nc(){return super.nc()*this.Xc}Kb(){this.Xc=this.Ga||this.Ab()?0:1;this.Lb()}tc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Ea(){let g=this.pa;this.Uc&&(g*=this.i.ec);this.j&&(this.j.playbackRate.value=g)}sc(g){this.I||this.T()||(this.H?this.N=g:(this.Va(),this.N=g,this.Bb()))}oc(){return this.N}uc(g){g?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Yb=this.yb(),this.Xb=this.N,this.ka=!1)}Cc(g){super.Cc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Od=-1;this.R=this.Y="";this.g=null}c(){this.f=null}bg(a){this.Od=a}jg(a){this.Y=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var m=this.f.currentTime;h+=m;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,h)}}}Sa(){return{type:this.R,tag:this.Y,params:this.g}}}
self.je=class extends g{constructor(a,b,d,h,m,p,w){super(a);this.R="filter";this.g=[b,d,h,m,p,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=h;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,h);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,h);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,h);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,h)}}};self.he=class extends g{constructor(a,b,d,h){super(a);this.R="delay";this.g=[b,d,h];this.l=
this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=1-h;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=d;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){const m=self.da.jd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 4:this.g[1]=m(b);this.m(this.cb.gain,m(b),d,h);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,h)}}};self.ge=class extends g{constructor(a,b,d,h){super(a);this.R="convolution";this.g=[d,h];this.Jd=this.Id="";this.l=this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=
1-h;this.bb=this.f.createConvolver();this.bb.normalize=d;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}Yf(a,b){this.Id=a;this.Jd=b}Sa(){const a=
super.Sa();a.bufferOriginalUrl=this.Id;a.bufferUrl="";a.bufferType=this.Jd;return a}};self.ke=class extends g{constructor(a,b,d,h,m,p){super(a);this.R="flanger";this.g=[b,d,h,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=h;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.J);this.J.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,h);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,h);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,d,h)}}};self.me=class extends g{constructor(a,b,d,h,m,p,w){super(a);this.R="phaser";this.g=[b,d,h,m,p,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=h;this.s=this.f.createOscillator();this.s.frequency.value=p;this.J=this.o();this.J.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.J);this.J.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,h);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,h);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,h);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,h);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,h)}}};self.le=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){const m=self.da.jd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,h)}}};self.oe=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.s.connect(this.J);this.J.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.J.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,h);this.m(this.J.gain,b/2,d,h);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,h)}}};self.ne=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.sb=this.o();this.sb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.sb.gain);this.s.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,h);
this.m(this.a.gain,1-b,d,h);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,h)}}};self.ie=class extends g{constructor(a,b,d,h,m,p){super(a);this.R="distortion";this.g=[b,d,h,m,p];this.l=this.o();this.bc=this.o();this.ac=this.o();this.Zf(h,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.fc=this.f.createWaveShaper();this.Nc=new Float32Array(65536);this.df(b,d);this.fc.curve=this.Nc;this.l.connect(this.bc);this.l.connect(this.a);this.bc.connect(this.fc);this.fc.connect(this.ac);
this.ac.connect(this.b)}c(){this.l.disconnect();this.bc.disconnect();this.fc.disconnect();this.ac.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Zf(a,b){.01>a&&(a=.01);this.bc.gain.value=a;this.ac.gain.value=Math.pow(1/a,.6)*b}df(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.lg(h,a,b);this.Nc[32768+d]=h;this.Nc[32768-d-1]=-h}}lg(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.da.Cg(h-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}};self.fe=class extends g{constructor(a,b,d,h,m,p){super(a);this.R="compressor";this.g=[b,d,h,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=h;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ee=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Md=new Float32Array(this.h.frequencyBinCount);this.Yd=new Uint8Array(b);this.Wd=this.Ka=0;this.i.Oe(this)}c(){this.i.Rf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Md);this.h.getByteTimeDomainData(this.Yd);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let h=(this.Yd[d]-128)/128;0>h&&(h=-h);
this.Ka<h&&(this.Ka=h);b+=h*h}d=self.da.Ee;this.Ka=d(this.Ka);this.Wd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}ye(){return{tag:this.Y,index:this.Od,peak:this.Ka,rms:this.Wd,binCount:this.h.frequencyBinCount,freqBins:this.Md}}}};
